// import { Inter } from 'next/font/google'
import "../../public/css/globals.css";
import "../../public/js/script.js";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by csreate next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
